Feature/youtube screen
tbskgm0/flutter-tutorial pull request #1
Opened 2022-05-20 03:06 UTC by tbskgm0

YoutubeScreenの画面を作成しました。確認お願いいたします。
Developブランチ作るの忘れてました。

2022-05-22 14:25 UTC, t-nakata requested changes

2022-05-22 14:25 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  AppBar _YoutubeAppBar(BuildContext context) {
メソッドは動詞で始めるようにしてください。
このメソッドはWidgetをBuildして返却するので `build~~`というメソッド名にするとわかりやすくなると思います。


また、頭に`_`をつけるとしても、はじめの`Y`は小文字で記載するのが普通です。

2022-05-22 14:25 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget _YoutubeBody() {
このメソッド名も同上です

2022-05-22 14:25 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget _GenreItems() {
こちらも同上

2022-05-22 14:25 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +    ];
1. メソッド内のローカル変数なので、頭の `_`はいらないと思います。
2. 名前に統一感がないので、もう少し名前を考えたほうがいいと思いました。
   - メソッド名がgenreItems
   - モデルクラスが ItemInformation
   - ItemInformationのListなのにgenreList

2022-05-22 14:25 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +            for (final category in _genreList)
こちらも同上で、genreListの要素を表す変数名なのに category で 中身を作るメソッドがcategoryButton
やっぱり統一感がないと思います。

2022-05-22 14:25 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget _categoryButton(String text, IconData icon, MaterialColor color) {
こちらのメソッド名も動詞で始めるようにしてください。

2022-05-22 14:25 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget _movieButton() {
これもメソッド名の見直し

2022-05-22 14:25 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget _movieCell(Image image, String icon, String title, String channel,
これもメソッド名の見直し

2022-05-22 14:25 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget _BottomNavigationBar() {
これもメソッド名の見直し

2022-05-22 14:25 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  String title;
Structに Imageという Widgetが入っていることに違和感があります。
本来なら画像Pathを入れておいて Cell生成時にImage Widgetを生成するのが普通だと思います。

そもそも、JsonにWidgetは入らないですしね。

2022-05-23 13:26 UTC, tbskgm0 commented on lib/youtube/youtube_screen.dart
> +  AppBar _YoutubeAppBar(BuildContext context) {
修正しました！

2022-05-23 13:30 UTC, tbskgm0 commented on lib/youtube/youtube_screen.dart
> +    ];
修正しました！

2022-05-23 13:31 UTC, tbskgm0 commented on lib/youtube/youtube_screen.dart
> +            for (final category in _genreList)
修正しました！

2022-05-23 13:33 UTC, tbskgm0 commented on lib/youtube/youtube_screen.dart
> +  Widget _categoryButton(String text, IconData icon, MaterialColor color) {
修正しました。

2022-05-23 13:33 UTC, tbskgm0 commented on lib/youtube/youtube_screen.dart
> +  Widget _movieButton() {
修正しました。

2022-05-23 14:35 UTC, tbskgm0 commented on lib/youtube/youtube_screen.dart
> +  String title;
String型に修正しました。

2022-05-23 14:37 UTC, tbskgm0 commented on lib/youtube/youtube_screen.dart
> +  Widget _BottomNavigationBar() {
修正しました。

2022-05-28 10:05 UTC, merged